### ISSUE TITLE
Templates for forms are not working

### ISSUE THREAD

**Issue by lyz452** [Holt59/cakephp3-bootstrap-helpers#50]
I saw someone previously asked how to use templates but when I tried to use myself to add a class to the error messages it didn't work.

The example given was:

    public $helpers = [
        'Form' => [
            'className' => 'Bootstrap3.BootstrapFormHelper',
                'templates' => [
                    'dateWidget' => '{{day}}{{month}}{{year}}{{hour}}{{minute}}{{second}}{{meridian}}'
                ]
        ]
    ];

so in my code:

    public $helpers = [
        'Form' => [
            'className' => 'Bootstrap.BootstrapForm',
            'templates' => [
                'error' => '<span class="help-block error-message">{{content}}</span>'
            ],
        ],
    ];

but my error messages did not change. I still only have the class .help-block (which is not helpful for styling if you plan to use .help-block for information purposes in your form)

**Comment by Holt59** [comment]
Hi,

It is currently not possible to have custom templates for `formGroup`, `checkboxContainer`, `radioContainer` `submitContainer`, `label`, and `error`.

I have just push an update where I added `error-message` class form the errors. I will try to correct the template problem in a future update but I think it will not be that easy because of the automatic management of horizontal forms...

**Comment by Holt59** [comment]
This should be solved with https://github.com/Holt59/cakephp3-bootstrap-helpers/commit/e4fad5e81b64f4e6438ca5ef5a3245e77df1f77e, but be careful if you modify one of the mentioned template since they contained additional template variables that may break the helper if you forget them!
