### ISSUE TITLE
Paginator numbers

### ISSUE THREAD

**Issue by Benoit382** [Holt59/cakephp3-bootstrap-helpers#66]
How can I use icon for prev/next ?

Is it possible to use the paginator like this :
```php
<?= $this->Paginator->numbers([
        'prev'=>['title'=>$this->Html->icon('chevron-left'),'escape'=>false],
        'next'=>['title'=>$this->Html->icon('chevron-right'),'escape'=>false]]); ?>
```

Proposal :
```php
if (isset($options['prev'])) {
	$title  = '';
	$opt    = [];
	if(is_array($options['prev'])){
		$opt    = $options['prev'];
		$title  = $opt['title'];
		unset($opt['title']);
	}else{
		$title = $options['prev'];
	}
	$options['before'] .= $this->prev($title,$opt) ;
}
```

**Comment by Holt59** [comment]
Hi,

Sorry to answer so lately. I have added your code to the paginator, so you can do:

```php
<?= $this->Paginator->numbers([
        'prev'=>['title'=>$this->Html->icon('chevron-left'),'escape'=>false],
        'next'=>['title'=>$this->Html->icon('chevron-right'),'escape'=>false]]); ?>
```

I also started to add a way to use "easy icon", and I have updated `BootstrapPaginator::prev` and `BootstrapPaginator::next` so you can simply do:

```php
<?= $this->Paginator->numbers([
        'prev'=> 'i:chevron-left',
        'next'=> 'i:chevron-right']); ?>
```

To get the same result. Note that the format `i:icon-name` is specific to this plugin, and currently only works with the `prev` and `next` methods of the paginator (also works with `numbers` since `numbers` uses `prev` and `next`).

In a future update, it will be possible to use `i:icon-name` in various places such as breadcrumbs, button, etc.

Mikael
