### ISSUE TITLE
Add pagination support for first and last 

### ISSUE THREAD

**Issue by Antoniossss** [Holt59/cakephp3-bootstrap-helpers#75]
Right now i am using following code:

```
<?= $this->Paginator->numbers([
       "size"=>"large",
       "prev"=>"i:chevron-left",
       "next"=>"i:chevron-right"
        ]);?>
```

and this generates pagination with prev next buttons. Please add support to append first/last buttons to pogaination as well.
Using next() and prev() causes generation of separate unordered lists. 

Maybe i am using it wrong?

**Comment by Holt59** [comment]
This is clearly a bug that I was aware of but I simply forgot to fix it, I will try to publish a patch ASAP.

**Comment by Holt59** [comment]
Should be fixed by 167385c0e085eab3f9ebf4e4d940dafe13191c56, feel free to try it!

**Comment by Antoniossss** [comment]
would be very nic3
21 lut 2016 13:25 "Mikaël Capelle" <notifications@github.com> napisał(a):

**Comment by Antoniossss** [comment]
Ic checked out provided commit (current head i belive) and i have no navigation buttons at all (besides numers)

![przechwytywanie](https://cloud.githubusercontent.com/assets/7877627/13216754/2aa5863a-d95e-11e5-918f-8743a63ea23f.PNG)

And using code similar to the one above:

````
 $this->Paginator->numbers([
                            "size" => "large",
                            "first"=>"<<",
                            "last"=>">>",
                            "prev" => "i:chevron-left",
                            "next" => "i:chevron-right",
                            "class" => "no-margin"
                        ]);
````

**Comment by Holt59** [comment]
I did not test it using small datasets and it seems to not be working with small datasets (the ones that do not call `_modulusNumbers`. I have made a new update, that should work with any dataset, but I did not test it that much so it may still be buggy...

**Comment by Antoniossss** [comment]
![przechwytywanie](https://cloud.githubusercontent.com/assets/7877627/13222163/faf4afb2-d97e-11e5-832e-2f82a5b04a17.PNG)

Are those dotted buttons (always disabled) intentional?
Works better now, last first buttons shows only if there is indeed more pages that are not listed yet (cool feature i think)

**Comment by Holt59** [comment]
These dotted buttons are `ellipsis` created by Cake itself. I think these are already presents with the default Paginator helper (you can check). 

It should not be that difficult to add a custom option to disable it.

**Comment by Antoniossss** [comment]
You are right, but looks like there are not working as supposed to work in cake's pagination helper.
Anyway, current head is working so bug is fixed. Thank you for quick respose.

**Comment by Holt59** [comment]
What do you mean by *there are not working as supposed to work in cake's pagination helper*?

**Comment by Antoniossss** [comment]
I just dont follow what they supposed to to mean.

It would make sense to add them like this:
| < Last | 1 | 2 | ... | 10 | 11 | 12 | 13 | 14 | 15 | ... | 56 | 57 | >Next |

so it should either show first and/or last link, OR use ellipsis to allow first and last page to be listed in pagination so user can go to last page by clicking on it. But if there is a last,first link displayed then elipsis could be ommited. 

And the docs specifies that :

>     The generated number links will include the 'ellipsis' template when the `first` and `last` options
     and the number of pages exceed the modulus. For example if you have 25 pages, and use the first/last
     options and a modulus of 8, ellipsis content will be inserted after the first and last link sets.

So if I understand right it would be like 

| .. | <pref | 5 | 6 | 7 | 8 | >next | ... |
and that seems to be wrong/useless IMHO.

**Comment by Holt59** [comment]
I understand what you are saying. Actually, the behavior of Cake is the following:
- If `last` (or `first`) is not an `int`, then it is used as the text for a link to the last page, and an ellipsis (`...`) is added before (or after) if there are pages that are not visible in the current numbers (e.g. you have 20 pages, but the last visible page number is 12).
- If `last` (or `first`) is an `int`, then you get link to the `N` last pages (where `N = last`) with an ellipsis before, e.g. if `last` is 4 you get `1 | 2 | 3 | ... | 59 | 60 | 61 | 62`.

Cake's behavior for `first` and `last` options is perfectly right, the problem arises when you try to add `next` and `prev` buttons which are not available in the default `Paginator` helper. Since the ellipsis is part of the `last` and `first` block (these are generated by `_firstNumber` and `_lastNumber`), the `prev` and `next` are added between the ellipsis and the numbers.

Having something like this:
```
< Prev | 1 | 2 | ... | 10 | 11 | 12 | 13 | ... | 38 | 39 | > Next
```

Seems right to me, but what about the following:
```
< Prev | << First | 10 | 11 | 12 | 13 | >> Last | > Next
```

Looks strange IMO... Maybe the first case should be chosen when `first` / `last` is an `int`, and keep the current behavior (without ellipsis) if it is a string? What do you think?

**Comment by Holt59** [comment]
I have implemented the mentioned behavior in the latest commit, feel free to test it and tell me what you think of the output.

**Comment by Antoniossss** [comment]
< Prev | << First | is not intuitive as you would expect the opposite order. 

I will have to wait with testing till we update to cake 3.2~ as this is the required dependency for helpers now.

**Comment by Holt59** [comment]
You can check the new behaviour with the `v3.0.5` release which still require CakePHP `~3.0`.
