### ISSUE TITLE
HtmlHelper::progress does not output the sr-only text

### ISSUE THREAD

**Issue by nrother** [Holt59/cakephp3-bootstrap-helpers#87]
As per [doc](http://getbootstrap.com/components/#progress) every bar `div` should contain a `span.sr-only` with something like "x% Complete"
`<span class="sr-only">60% Complete</span>`

This is currently not included by `HtmlHelper::progress` :smile: It would also be nice if there would be a option to remove the class `sr-only` to have a visible progress text.

**Comment by Holt59** [comment]
This should now be fixed by e34e0d6db6336556669a20dc96a6744e4f1f20c2 - The `sr-only` span should always be rendered, and you can set the `'display' => true` option to remove the 'sr-only' class of the span. 

You can also change the format of the text by setting the `progressTextFormat` options on the `BootstrapFormHelper`.
