### ISSUE TITLE
Add support for ['escape' => false] for Flash element

### ISSUE THREAD

**Issue by nrother** [Holt59/cakephp3-bootstrap-helpers#89]
Currently all flash templates always escape there content with `h()`. It would be nice if this could be turned off using `['escape' => false]` as in the official templates.

**Comment by Holt59** [comment]
Sorry for the delay.

The standard `FlashHelper` has been modified recently and I can't find the new template but according to the [documentation](http://book.cakephp.org/3.0/en/views/helpers/flash.html) the standard behavior is to not escape anything (without the possibility to `['escape' => true]`).

I will try to update the `BootstrapFlashHelper` as soon as I can.

**Comment by nrother** [comment]
The default templates are part of the [app template](https://github.com/cakephp/app/blob/master/src/Template/Element/Flash/default.ctp). The templates escape the message, that's probably why the helper won't do it.

**Comment by Holt59** [comment]
Again, sorry for the delay... I just pushed a new version with "correct" behaviour - fa2a71accffdb763d70a8dfbaa8e6ba6e6b03673.

I wanted to do something a bit more generic but I ended up simply adding the `if () { ... }` block inside the elements since the CakePHP official doc is kind of disturbing... The [**Flash Component**](http://book.cakephp.org/3.0/en/controllers/components/flash.html) documentation says:

> By default, CakePHP escapes the content in flash messages for security reasons. If you are using any request or user data in your flash messages those are escaped and therefore safe to be printed. If you want to output HTML, you need to pass in an escape param and also adjust the templates to allow disabling escaping when such a param is passed.

While the [**Flash Helper**](http://book.cakephp.org/3.0/en/views/helpers/flash.html) documentation says:

> By default, CakePHP does not escape the HTML in flash messages. If you are using any request or user data in your flash messages, you should escape it with h when formatting your messages.

I yet have to try with the latest CakePHP version but on my version, the only escaping done are in the `.ctp`, meaning that custom flash elements are not escaped by default... This is kind of strange for me, maybe you can give a feedback on this part of the doc before I raise an "issue" on the CakePHP repository?

**Comment by nrother** [comment]
Thanks for the new version 👍 

I just checked the source of the [FlashComponent](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/FlashComponent.php), and there is absolutely no escaping. That section of the doc seems wrong. I'm fine with posting an issue. Unfortunately the docs are often confusing/misleading 😦
